import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms of Service — Resu-Dog",
  description: "Terms and conditions for using Resu-Dog AI resume optimization.",
};

export default function TermsPage() {
  return (
    <div className="mx-auto max-w-3xl px-4 py-16 sm:px-6 lg:px-8">
      <h1 className="text-3xl font-extrabold tracking-tight mb-2">Terms of Service</h1>
      <p className="text-sm text-foreground-muted mb-10">Last updated: April 2026</p>

      <div className="prose prose-sm prose-invert max-w-none space-y-8 text-foreground-soft leading-relaxed">

        <section>
          <h2 className="text-lg font-semibold text-foreground mb-2">1. Service description</h2>
          <p>
            Resu-Dog is an AI-powered tool that optimizes resumes for ATS compatibility, generates cover letters,
            produces skills gap analyses, and creates shareable profile pages. The service uses OpenAI&apos;s GPT-4o
            model to process your content.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-foreground mb-2">2. Acceptable use</h2>
          <p>You agree to:</p>
          <ul className="list-disc pl-5 space-y-1">
            <li>Provide only your own resume content or content you have permission to use.</li>
            <li>Not use the service to generate fraudulent credentials, fabricated experience, or misleading information.</li>
            <li>Not attempt to reverse-engineer, abuse, or overload the service.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-foreground mb-2">3. AI-generated content</h2>
          <p>
            Resu-Dog uses AI to rewrite and optimize your resume. While we instruct the AI to never fabricate
            experience, dates, companies, or qualifications, you are responsible for reviewing all output for accuracy
            before using it in job applications. AI-generated content may contain errors.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-foreground mb-2">4. Intellectual property</h2>
          <p>
            You retain full ownership of your resume content. Optimized output generated by the service is yours
            to use without restriction. Resu-Dog does not claim any rights over your content.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-foreground mb-2">5. Limitation of liability</h2>
          <p>
            Resu-Dog is provided &ldquo;as is&rdquo; without warranty. We are not liable for any hiring outcomes,
            application rejections, or damages arising from the use of AI-generated content. The service is a tool
            to assist your job search — it does not guarantee results.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-foreground mb-2">6. Service availability</h2>
          <p>
            We aim to keep Resu-Dog available at all times but do not guarantee uptime. The service depends on
            third-party APIs (OpenAI, Vercel) and may be temporarily unavailable due to maintenance or outages
            beyond our control.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-foreground mb-2">7. Changes to terms</h2>
          <p>
            We may update these terms from time to time. Continued use of the service constitutes acceptance of
            the updated terms.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-foreground mb-2">8. Contact</h2>
          <p>
            Questions about these terms? Email us at{" "}
            <a href="mailto:legal@resu-dog.com" className="text-primary hover:underline">
              legal@resu-dog.com
            </a>.
          </p>
        </section>

      </div>

      <div className="mt-12 pt-6 border-t border-line">
        <Link href="/privacy" className="text-sm text-primary hover:underline">
          ← Privacy Policy
        </Link>
      </div>
    </div>
  );
}
